# Generated by Django 5.0.4 on 2024-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="occupationhistory",
            options={"verbose_name_plural": "Occupation Histories"},
        ),
        migrations.RemoveField(
            model_name="person",
            name="occupation",
        ),
        migrations.AlterField(
            model_name="occupationhistory",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
