# Generated by Django 4.2.11 on 2024-04-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="friends",
            new_name="collaborators",
        ),
        migrations.AddField(
            model_name="person",
            name="dob",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AddField(
            model_name="person",
            name="dod",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AddField(
            model_name="person",
            name="photograph",
            field=models.ImageField(default="unknown.jpg", upload_to=""),
        ),
    ]
