# Generated by Django 4.2.11 on 2024-04-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_rename_friends_person_collaborators_person_dob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="dob",
            field=models.DateField(default="2000-01-01", verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="person",
            name="dod",
            field=models.DateField(default="2000-01-01", verbose_name="Date of Death"),
        ),
    ]
