# Generated by Django 4.2.11 on 2024-04-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_person_notes_alter_person_dob_alter_person_dod"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="aliases",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
