# Generated by Django 5.0.4 on 2024-10-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_location_created_at_location_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Religion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("In-Holding", "In-Holding"),
                    ("Known Residence", "Known Residence"),
                    ("Allotment", "Allotment"),
                    ("Permit", "Permit"),
                    ("Unknown", "Unknown"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ReligiousAffiliation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_joined", models.DateField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="network.person"
                    ),
                ),
                (
                    "religion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="network.religion",
                    ),
                ),
            ],
            options={
                "unique_together": {("person", "religion")},
            },
        ),
        migrations.AddField(
            model_name="person",
            name="known_religious_affiliation",
            field=models.ManyToManyField(
                blank=True,
                related_name="religious_affiliations",
                through="network.ReligiousAffiliation",
                to="network.religion",
            ),
        ),
    ]
