# Generated by Django 5.0.4 on 2024-10-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_religion_location_location_type_location_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="political_affiliations",
        ),
        migrations.AlterField(
            model_name="religion",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Denomination"
            ),
        ),
        migrations.CreateModel(
            name="PoliticalAffiliationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="network.person"
                    ),
                ),
                (
                    "political_affiliation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="network.politicalaffiliation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Political Affiliation Histories",
            },
        ),
        migrations.AddField(
            model_name="person",
            name="known_political_affiliations",
            field=models.ManyToManyField(
                blank=True,
                related_name="political_affiliations",
                through="network.PoliticalAffiliationHistory",
                to="network.politicalaffiliation",
            ),
        ),
    ]
