# Generated by Django 4.2.11 on 2024-04-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_person_aliases"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="email",
        ),
    ]
