# Generated by Django 4.2.11 on 2024-04-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_remove_person_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="events",
            field=models.ManyToManyField(
                related_name="locations", to="network.location"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dob",
            field=models.DateField(
                blank=True, default="2000-01-01", verbose_name="Date of Birth"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dod",
            field=models.DateField(
                blank=True, default="2000-01-01", verbose_name="Date of Death"
            ),
        ),
    ]
