# Generated by Django 4.2.11 on 2024-04-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0006_alter_location_events_alter_person_dob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="farm_ranch_location",
            field=models.ManyToManyField(
                related_name="farmers_ranchers", to="network.location"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="home",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="residents",
                to="network.location",
            ),
        ),
    ]
