# Generated by Django 4.2.11 on 2024-04-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_person_farm_ranch_location_person_home"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="name",
        ),
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="location",
            name="state",
            field=models.CharField(
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DE", "Delaware"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("KY", "Kentucky"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WV", "West Virginia"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                ],
                default=1,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                related_name="locations",
                to="network.location",
                verbose_name="Known events",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True, to="network.person", verbose_name="Known collaborators"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="farm_ranch_location",
            field=models.ManyToManyField(
                blank=True, related_name="farmers_ranchers", to="network.location"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="home",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="residents",
                to="network.location",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="photograph",
            field=models.ImageField(blank=True, default="unknown.jpg", upload_to=""),
        ),
    ]
