# Generated by Django 4.2.11 on 2024-04-11 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0008_remove_location_name_location_city_location_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="event_attendee", to="network.person"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_location",
                to="network.location",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                related_name="locations",
                to="network.event",
                verbose_name="Known events",
            ),
        ),
    ]
