# Generated by Django 4.2.11 on 2024-04-11 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0009_alter_event_attendees_alter_event_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="criminal_charges",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="criminal_charges_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="person",
            name="occupation",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="political_affiliations",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="FamilyMemberRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relation_type", models.CharField(blank=True, max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="network.person",
                    ),
                ),
                (
                    "related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reverse_relationships",
                        to="network.person",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="relatives",
            field=models.ManyToManyField(
                through="network.FamilyMemberRelationship", to="network.person"
            ),
        ),
    ]
