# Generated by Django 4.2.11 on 2024-04-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0010_person_criminal_charges_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymemberrelationship",
            name="relation_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                related_name="locations",
                to="network.event",
                verbose_name="Known events at this location",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="farm_ranch_location",
            field=models.ManyToManyField(
                blank=True,
                related_name="farmers_ranchers",
                to="network.location",
                verbose_name="Farm or ranch location(s)",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="relatives",
            field=models.ManyToManyField(
                blank=True,
                through="network.FamilyMemberRelationship",
                to="network.person",
            ),
        ),
    ]
