# Generated by Django 4.2.11 on 2024-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0012_remove_person_name_person_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="person",
            name="aliases",
        ),
        migrations.AddField(
            model_name="person",
            name="aliases",
            field=models.ManyToManyField(blank=True, to="network.alias"),
        ),
    ]
