# Generated by Django 4.2.11 on 2024-04-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0013_alias_remove_person_aliases_person_aliases"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoliticalAffiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="person",
            name="political_affiliations",
        ),
        migrations.AddField(
            model_name="person",
            name="political_affiliations",
            field=models.ManyToManyField(blank=True, to="network.politicalaffiliation"),
        ),
    ]
