# Generated by Django 4.2.11 on 2024-04-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0014_politicalaffiliation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="dob",
            field=models.DateField(
                blank=True,
                default="2000-01-01",
                null=True,
                verbose_name="Date of Birth",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="dod",
            field=models.DateField(
                blank=True,
                default="2000-01-01",
                null=True,
                verbose_name="Date of Death",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="photograph",
            field=models.ImageField(
                blank=True, default="unknown.jpg", null=True, upload_to=""
            ),
        ),
    ]
