# Generated by Django 4.2.11 on 2024-04-11 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0015_alter_person_dob_alter_person_dod_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymemberrelationship",
            name="relation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Parent", "Parent"),
                    ("Child", "Child"),
                    ("Sibling", "Sibling"),
                    ("Spouse", "Spouse"),
                    ("Partner", "Partner"),
                    ("Friend", "Friend"),
                    ("Colleague", "Colleague"),
                    ("Mentor", "Mentor"),
                    ("Student", "Student"),
                    ("Teacher", "Teacher"),
                    ("Business Partner", "Business Partner"),
                    ("Grandparent", "Grandparent"),
                    ("Grandchild", "Grandchild"),
                    ("Aunt", "Aunt"),
                    ("Uncle", "Uncle"),
                    ("Niece", "Niece"),
                    ("Nephew", "Nephew"),
                    ("Cousin", "Cousin"),
                    ("Guardian", "Guardian"),
                    ("Caretaker", "Caretaker"),
                    ("Roommate", "Roommate"),
                    ("Neighbor", "Neighbor"),
                    ("Acquaintance", "Acquaintance"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="home",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="residents",
                to="network.location",
            ),
        ),
    ]
