# Generated by Django 4.2.11 on 2024-04-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0017_remove_event_attendees_eventattendance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.AddField(
            model_name="event",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="date_start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
